spring:
  profiles:
    active:
    - memory  
  jackson:
    date-format: yyyy-MM-dd
    locale: zh_TW
    time-zone: GMT+8 
    
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'
app:
  description: '@tmf-version@' 
server:
  port: 9000
  forward-headers-strategy: framework
  servlet:
    context-path: /auth
  
jasypt:
  encryptor:
    password: nca
logging:  
  level:
    org.springframework: DEBUG
    org.springframework.web: ERROR
 
---
spring:
  config:
    activate:
      on-profile: mssql 
  datasource:
    username: sa
    password: ENC(USSQQJG+zy7EHGoUQ3qJLLoiqi5hwJcI20GqhATi+QMWVjf4AVCRFtJXlRtyaAYn)
    url: jdbc:sqlserver://localhost;databaseName=rds;encrypt=false;integratedSecurity=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
        
---
spring:
  config:
    activate:
      on-profile: oracle 
  datasource:
    username: yourname
    password: yourpassword
    url: jdbc:oracle:thin:@localhost:1521/LST
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    username: sa
    url: jdbc:h2:./data/keycloak;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: memory        